name: CI

on:
  push:
    paths:
      - "**"
  pull_request:
    paths:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Formatting check (black)
        run: |
          black --version
          black --check .

      - name: Lint (flake8)
        run: |
          flake8 .

      - name: Type check (mypy)
        run: |
          mypy .

      - name: Run tests
        run: |
          pytest -q